require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false

Metrics:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: compact

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 100
