AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Metrics:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 100
