name: lint

on:
  push:
    branches-ignore: [release]
    paths:
      - "lib/**"
      - "test/**"
      - "pkgcraft.gemspec"
      - "Gemfile"
      - "Rakefile"
      - ".rubocop.yml"
      - ".github/workflows/lint.yml"
  pull_request:
    branches: [main]
    paths:
      - "lib/**"
      - "test/**"
      - "pkgcraft.gemspec"
      - "Gemfile"
      - "Rakefile"
      - ".rubocop.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Lint code
      run: bundle exec rake rubocop
